{% set name = "gstools" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3187fc800b3ae0245bef391dc492f0d7256d980dd8c488e36274f53aba9e6226

build:
  skip: True         # [python_impl == 'pypy']
  number: 0
  script_env:
    - GSTOOLS_BUILD_PARALLEL=1
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - llvm-openmp
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - llvm-openmp
    - pip
    - python
    - toml
    - setuptools >=45
    - setuptools_scm >=3.5
    - cython >=0.28.3, <3.0
    - numpy >=1.14.5, <2.0
  run:
    - llvm-openmp
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.1.0, <2.0
    - emcee >=3.0.0, <4.0
    - hankel >=1.0.2, <2.0
    - pyevtk >=1.1.1, <2.0
    - meshio >=4.0.3, <5.0

test:
  imports:
    - gstools
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/GSTools
  license: GNU Lesser General Public v3 (LGPLv3)
  license_family: LGPL
  license_file: LICENSE
  summary: 'GSTools: A geostatistical toolbox.'
  description: |
    GeoStatTools provides geostatistical tools for various purposes:
    - random field generation
    - simple, ordinary, universal and external drift kriging
    - conditioned field generation
    - incompressible random vector field generation
    - (automatted) variogram estimation and fitting
    - directional variogram estimation and modelling
    - data normalization and transformation
    - many readily provided and even user-defined covariance models
    - metric spatio-temporal modelling
    - plotting and exporting routines
  doc_url: https://gstools.readthedocs.io
  dev_url: https://github.com/GeoStat-Framework/GSTools

extra:
  recipe-maintainers:
    - MuellerSeb
    - LSchueler
