{% set name = "gstools" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14f6b1f276c63b03260d0159afab122dfc4e122dd58676f684d25d8ec33eb016

build:
  number: 0
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps --global-option="--openmp" -vv   # [not (osx and py>=37 or win)]
    - {{ PYTHON }} -m pip install . --no-deps -vv                              # [osx and py>=37 or win]

requirements:
  build:
    - llvm-openmp  # [not (osx and py>=37 or win)]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - llvm-openmp  # [not (osx and py>=37 or win)]
    - pip
    - python
    - setuptools >=45
    - setuptools_scm >=3.4
    - cython >=0.28.3
    - numpy >=1.14.5
  run:
    - llvm-openmp  # [not (osx and py>=37 or win)]
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.1.0
    - emcee >=3.0.0
    - hankel >=1.0.2
    - pyevtk >=1.1.1

test:
  imports:
    - gstools
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/GSTools
  license: GNU Lesser General Public v3 (LGPLv3)
  license_family: LGPL
  license_file: LICENSE
  summary: 'GSTools: A geostatistical toolbox.'
  description: |
    GeoStatTools provides geostatistical tools for various purposes:
    - random field generation
    - conditioned field generation
    - incompressible random vector field generation
    - simple and ordinary kriging
    - variogram estimation and fitting
    - many readily provided and even user-defined covariance models
    - plotting and exporting routines
  doc_url: https://geostat-framework.readthedocs.io/projects/gstools
  dev_url: https://github.com/GeoStat-Framework/GSTools

extra:
  recipe-maintainers:
    - MuellerSeb
    - LSchueler
