{% set name = "gstools" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3be5f1a6f33805cc2c4de8fb6feaede5e957c41da19c020b774c08ea9168578c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --global-option="--openmp" -vv

requirements:
  build:
    - llvm-openmp  # [not (win and py2k)]
    - {{ compiler('c') }}
  host:
    - llvm-openmp  # [not (win and py2k)]
    - python
    - pip
    - setuptools
    - cython >=0.28.3
    - numpy >=1.14.5
  run:
    - llvm-openmp  # [not (win and py2k)]
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.1.0
    - emcee >=3.0.0
    - hankel >=0.3.6
    - pyevtk
    - six

test:
  imports:
    - gstools
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/GSTools
  license: GNU Lesser General Public v3 (LGPLv3)
  license_family: LGPL
  license_file: LICENSE
  summary: 'GSTools: A geostatistical toolbox.'
  description: |
    GeoStatTools provides geostatistical tools for various purposes:
    - random field generation
    - conditioned field generation
    - incompressible random vector field generation
    - simple and ordinary kriging
    - variogram estimation and fitting
    - many readily provided and even user-defined covariance models
    - plotting and exporting routines
  doc_url: https://geostat-framework.readthedocs.io/projects/gstools
  dev_url: https://github.com/GeoStat-Framework/GSTools

extra:
  recipe-maintainers:
    - MuellerSeb
    - LSchueler
